# Part of the Ziv Programming Language, under the Apache License v2.0 with LLVM
# See /LICENSE for license details.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: ziv
          cache-environment: true
          cache-downloads: true

      - name: Check Format
        shell: micromamba-shell {0}
        run: |
          pre-commit run --all-files
          clang-format --dry-run --Werror $(find . -name "*.cpp" -o -name "*.hpp")

  build:
    needs: format
    name: Build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-64
          - os: macos-latest
            platform: osx-64
          - os: windows-latest
            platform: win-64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: ziv
          cache-environment: true
          cache-downloads: true
          platform: ${{ matrix.platform }}

      - name: Cache ccache files
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-ccache-

      - name: Configure ccache
        shell: micromamba-shell {0}
        run: |
          ccache --max-size=2G
          ccache --zero-stats

      - name: Configure CMake
        shell: micromamba-shell {0}
        run: |
          cmake -B build -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DZIV_ENABLE_TESTING=ON \
                -DZIV_WARNINGS_AS_ERRORS=ON

      - name: Build
        shell: micromamba-shell {0}
        run: cmake --build build

      - name: Print ccache stats
        shell: micromamba-shell {0}
        run: ccache --show-stats

      # Cache the build for testing
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.platform }}
          path: build

  test:
    needs: build
    name: Test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-64
          - os: macos-latest
            platform: osx-64
          - os: windows-latest
            platform: win-64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: ziv
          cache-environment: true
          cache-downloads: true
          platform: ${{ matrix.platform }}

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-${{ matrix.platform }}
          path: build

      - name: Test
        shell: micromamba-shell {0}
        working-directory: build
        run: ctest --output-on-failure -V
