# Part of the Ziv Programming Language, under the Apache License v2.0 with LLVM
# See /LICENSE for license details.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Update Changelog

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 on the first day of every month
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Update Changelog
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python .github/scripts/update_changelog.py

      - name: Set Current Month-Year
        id: date
        run: echo "month_year=$(date '+%B %Y')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ github.token }}
          commit-message: 'docs: update changelog for ${{ steps.date.outputs.month_year }}'
          sign-commits: true
          title: 'docs: Update Changelog for ${{ steps.date.outputs.month_year }}'
          body: |
            \U0001f916 Automated changelog update
            
            This PR adds changes for ${{ steps.date.outputs.month_year }} to the changelog.
            
            Please review the changes and merge if they look correct.
          branch: ci/update-changelog
          base: main
          delete-branch: true
          labels: documentation
